const MESSAGES: string[] = [
    "The love of a family is life's greatest blessing.",
    "It's sad when someone you know becomes someone you knew.",
    "Family is the anchor that holds us steady in the rough waters of life.",
    "First thing every morning before you arise say out loud, 'I believe,' three times.",
    "Don't wait. The time will never be just right.",
    "It's sad when someone you know becomes someone you knew.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
];